// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {noteContent} from "./external-tokens.ts"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQQOPOOOVOPO'#C`O[OQO'#C_OOOO'#Cd'#CdQQOPOOOaOPO,58zOOOO'#Cc'#CcOOOO,58y,58yOOOO-E6b-E6bOfOPO1G.fOOOQ7+$Q7+$QOnOPO7+$QOOOQ<<Gl<<Gl",
  stateData: "s~OYPO~OZTO~OPUO~OTXO~OUZOYYO~OY[O~O",
  goto: "kXPPPY^PPbeTROSTQOSRVQQSORWS",
  nodeNames: "⚠ NoteInnerContent Document Note NoteDelimiter NoteLanguage Auto NoteContent",
  maxTerm: 11,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "&w~RXYZn}!Os#[#]!O#^#_!g#a#b$R#d#e%Q#g#h%j#h#i%p%&x%&y&f~sOY~~vP#T#Uy~!OOU~~!RP#h#i!U~!XP#a#b![~!_P#`#a!b~!gOT~~!jQ#T#U!p#g#h#r~!sP#j#k!v~!yP#T#U!|~#PP#g#h#S~#VP#V#W#Y~#]P#f#g#`~#cP#]#^#f~#iP#d#e#l~#oP#h#i!b~#uQ#c#d#{#l#m!b~$OP#b#c!b~$UP#T#U$X~$[Q#f#g$b#h#i$z~$eP#_#`$h~$kP#W#X$n~$qP#c#d$t~$wP#k#l#{~$}P#[#]!b~%TP#m#n%W~%ZP#h#i%^~%aP#[#]%d~%gP#c#d#{~%mP#e#f![~%sR#X#Y%|#g#h&S#m#n&Y~&PP#l#m#l~&VP#l#m!b~&]P#d#e&`~&cP#X#Y!|~&iP%&x%&y&l~&oP%&x%&y&r~&wOZ~",
  tokenizers: [0, noteContent],
  topRules: {"Document":[0,2]},
  tokenPrec: 0
})
