// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  NoteInnerContent = 1,
  Document = 2,
  Note = 3,
  NoteDelimiter = 4,
  NoteLanguage = 5,
  Auto = 6,
  NoteContent = 7
